const activities=[
{id:1,icon:'💧',title:'Quero água',context:'Estou com sede.',model:'Quando estou com sede, posso pedir água.',question:'O que eu posso pedir?',scene:'🧒  💧',success:'Eu quero água!',options:[['💧','Água',true],['🍎','Maçã',false],['🧸','Brinquedo',false],['📚','Livro',false]]},
{id:2,icon:'🍽️',title:'Quero comer',context:'Estou com fome.',model:'Quando estou com fome, posso pedir comida.',question:'O que eu posso pedir?',scene:'🧒  🍽️',success:'Eu quero comer!',options:[['🍽️','Comida',true],['🧸','Brinquedo',false],['📚','Livro',false],['⚽','Bola',false]]},
{id:3,icon:'🚻',title:'Quero ir ao banheiro',context:'Preciso ir ao banheiro.',model:'Eu posso avisar quando preciso ir ao banheiro.',question:'O que eu posso pedir?',scene:'🧒  🚻',success:'Quero ir ao banheiro!',options:[['🚻','Banheiro',true],['📚','Livro',false],['⚽','Bola',false],['🍎','Maçã',false]]},
{id:4,icon:'🙋',title:'Preciso de ajuda',context:'Não consigo fazer sozinho.',model:'Quando preciso, posso pedir ajuda.',question:'O que eu posso pedir?',scene:'🧒  🙋',success:'Preciso de ajuda!',options:[['🙋','Ajuda',true],['⚽','Bola',false],['🍎','Maçã',false],['📚','Livro',false]]},
{id:5,icon:'✅',title:'Quero / Não quero',context:'Eu posso mostrar minha escolha.',model:'Posso dizer quero ou não quero.',question:'Como posso mostrar minha escolha?',scene:'🧒  💬',success:'Eu posso escolher!',options:[['✅','Quero',true],['❌','Não quero',true]]}
];
let current=activities[0],independent=0,supported=0,neededHelp=false;const screens=['home','lesson','result'];
const settings=JSON.parse(localStorage.getItem('mundoSingularSettings')||'{"profile":"Criança A","support":"A","reduced":false,"quiet":false,"response":"Livre"}');
function renderHome(){document.getElementById('paths').innerHTML=activities.map(a=>`<article onclick="startLesson(${a.id})" role="button" tabindex="0"><span>${a.icon}</span><b>${a.title}</b><small>Atividade ${String(a.id).padStart(2,'0')}</small></article>`).join('');document.getElementById('profileName').textContent=settings.profile;document.getElementById('supportChip').textContent=`Apoio ${settings.support}`}
function show(id){screens.forEach(x=>document.getElementById(x).classList.toggle('active',x===id))}
function startLesson(id=current.id){current=activities.find(a=>a.id===id)||activities[0];independent=0;supported=0;neededHelp=false;document.getElementById('activityLabel').textContent=`ATIVIDADE ${String(current.id).padStart(2,'0')} • APOIO ${settings.support}`;document.getElementById('prompt').textContent=current.context;document.getElementById('instruction').textContent=current.model;document.getElementById('scene').textContent=current.scene;document.getElementById('next').classList.remove('hidden');document.getElementById('choices').classList.add('hidden');document.getElementById('feedback').textContent='';document.getElementById('bar').style.width='35%';show('lesson')}
function showChoice(){document.getElementById('prompt').textContent=current.question;document.getElementById('instruction').textContent=settings.support==='A'?'Escolha uma opção. Observe com calma.':'Escolha uma opção.';document.getElementById('scene').textContent=settings.support==='A'?current.scene:'🧒  💭';document.getElementById('next').classList.add('hidden');let opts=current.options;if(current.id!==5){opts=settings.support==='A'?opts.slice(0,2):settings.support==='B'?opts.slice(0,3):opts.slice(0,4)}const box=document.getElementById('choices');box.innerHTML=opts.map(o=>`<button onclick="answer(${o[2]})">${o[0]}<b>${o[1]}</b></button>`).join('');box.classList.remove('hidden');document.getElementById('bar').style.width='70%'}
function answer(ok){if(ok){if(neededHelp)supported++;else independent++;document.getElementById('feedback').textContent=`Muito bem. ${current.success}`;document.getElementById('scene').textContent='🧒  😊';document.getElementById('choices').classList.add('hidden');document.getElementById('bar').style.width='100%';setTimeout(finish,settings.reduced?250:700)}else{neededHelp=true;const target=current.options.find(o=>o[2]);document.getElementById('feedback').textContent=settings.support==='C'?'Tente novamente.':`Vamos tentar novamente. Procure: ${target[1]}`;if(settings.support==='A')document.getElementById('scene').textContent=`${target[0]}  ${target[1]}`}}
function finish(){document.getElementById('independent').textContent=independent;document.getElementById('supported').textContent=supported;document.getElementById('usedSupport').textContent=`Apoio ${settings.support}`;document.getElementById('resultText').innerHTML=`Você praticou: <b>${current.title}</b>.`;saveDemoResult();show('result')}
function saveDemoResult(){const key='mundoSingularDemo';const data=JSON.parse(localStorage.getItem(key)||'[]');data.push({profile:settings.profile,activity:current.title,supportLevel:settings.support,independent,supported,date:new Date().toLocaleString('pt-BR')});localStorage.setItem(key,JSON.stringify(data.slice(-30)))}
function restart(){startLesson(current.id)}function goHome(){show('home')}
document.getElementById('sensory').onclick=()=>{document.getElementById('demoProfile').value=settings.profile;document.getElementById('supportLevel').value=settings.support;document.getElementById('reduced').checked=settings.reduced;document.getElementById('quiet').checked=settings.quiet;document.getElementById('responseTime').value=settings.response;document.getElementById('panel').classList.remove('hidden')};
function closePanel(){settings.profile=document.getElementById('demoProfile').value;settings.support=document.getElementById('supportLevel').value;settings.reduced=document.getElementById('reduced').checked;settings.quiet=document.getElementById('quiet').checked;settings.response=document.getElementById('responseTime').value;localStorage.setItem('mundoSingularSettings',JSON.stringify(settings));document.getElementById('panel').classList.add('hidden');document.body.classList.toggle('reduced',settings.reduced);renderHome()}
document.body.classList.toggle('reduced',settings.reduced);renderHome();