const activities=[
{id:1,icon:'💧',title:'Quero água',context:'Léo está brincando e ficou com sede.',model:'Léo pode pedir: eu quero água.',question:'O que Léo pode pedir?',symbol:'💧',sceneImage:'assets/leo-estrelinha-3d.webp',success:'Eu quero água!',options:[['💧','Água',true],['🍎','Maçã',false],['🧸','Brinquedo',false],['📚','Livro',false]]},
{id:2,icon:'🍽️',title:'Quero comer',context:'Léo percebeu que está com fome.',model:'Léo pode pedir: eu quero comer.',question:'O que Léo pode pedir?',symbol:'🍽️',success:'Eu quero comer!',options:[['🍽️','Comida',true],['🧸','Brinquedo',false],['📚','Livro',false],['⚽','Bola',false]]},
{id:3,icon:'🚻',title:'Quero ir ao banheiro',context:'Léo precisa ir ao banheiro.',model:'Léo pode avisar: quero ir ao banheiro.',question:'O que Léo pode pedir?',symbol:'🚻',success:'Quero ir ao banheiro!',options:[['🚻','Banheiro',true],['📚','Livro',false],['⚽','Bola',false],['🍎','Maçã',false]]},
{id:4,icon:'🙋',title:'Preciso de ajuda',context:'Léo tentou e não conseguiu sozinho.',model:'Léo pode pedir: preciso de ajuda.',question:'O que Léo pode pedir?',symbol:'🧩',sceneImage:'assets/leo-estrelinha-3d.webp',success:'Preciso de ajuda!',options:[['🙋','Ajuda',true],['⚽','Bola',false],['🍎','Maçã',false],['📚','Livro',false]]},
{id:5,icon:'✅',title:'Quero / Não quero',context:'Léo pode mostrar o que prefere.',model:'Léo pode dizer quero ou não quero.',question:'Como Léo pode mostrar sua escolha?',symbol:'💬',success:'Eu posso escolher!',options:[['✅','Quero',true],['❌','Não quero',true]]}
];
let current=activities[0],independent=0,supported=0,neededHelp=false,lastNarration='';
const screens=['home','lesson','result'];
const settings=JSON.parse(localStorage.getItem('mundoSingularSettings')||'{"profile":"Criança A","support":"A","reduced":false,"quiet":false,"response":"Livre"}');
const $=id=>document.getElementById(id);
const paths=$('paths'),profileName=$('profileName'),supportChip=$('supportChip'),activityLabel=$('activityLabel'),prompt=$('prompt'),instruction=$('instruction'),scene=$('scene'),nextBtn=$('next'),choices=$('choices'),feedback=$('feedback'),bar=$('bar'),usedSupport=$('usedSupport'),resultText=$('resultText'),sensory=$('sensory'),panel=$('panel'),demoProfile=$('demoProfile'),supportLevel=$('supportLevel'),reduced=$('reduced'),quiet=$('quiet'),responseTime=$('responseTime');
function renderScene(activity,{success=false,hint=false}={}){
 if(activity.sceneImage){scene.innerHTML=`<div class="scene-3d-background" role="img" aria-label="Léo e Estrelinha 3D"></div>`;return;}
 const center=success?'⭐':hint?activity.options.find(o=>o[2])[0]:activity.symbol;
 scene.innerHTML=`<div class="character-scene scene-3d"><img src="assets/leo-estrelinha-3d.webp?v=20260827-12" alt="Léo e Estrelinha 3D"><div class="scene-symbol">${center}</div></div>`;
}
function speak(text){lastNarration=text;if(settings.quiet||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=settings.support==='A'?.78:settings.support==='B'?.9:1;window.speechSynthesis.speak(u)}
function repeatNarration(){speak(lastNarration||`${current.context} ${current.model}`)}
function renderHome(){paths.innerHTML=activities.map(a=>`<article onclick="startLesson(${a.id})"><span>${a.icon}</span><b>${a.title}</b><small>Aprender com Léo • ${String(a.id).padStart(2,'0')}</small></article>`).join('');profileName.textContent=settings.profile;supportChip.textContent=`Apoio ${settings.support}`}
function show(id){screens.forEach(x=>$(x).classList.toggle('active',x===id))}
function startLesson(id=current.id){current=activities.find(a=>a.id===id)||activities[0];independent=0;supported=0;neededHelp=false;activityLabel.textContent=`ATIVIDADE ${String(current.id).padStart(2,'0')} • APOIO ${settings.support}`;prompt.textContent=current.context;instruction.textContent=current.model;renderScene(current);nextBtn.classList.remove('hidden');choices.classList.add('hidden');feedback.textContent='';bar.style.width='35%';show('lesson');setTimeout(()=>speak(`${current.context} ${current.model}`),250)}
function showChoice(){prompt.textContent=current.question;const ins=settings.support==='A'?'Escolha uma opção. Observe com calma.':'Escolha uma opção.';instruction.textContent=ins;renderScene(current);nextBtn.classList.add('hidden');let opts=current.options;if(current.id!==5)opts=settings.support==='A'?opts.slice(0,2):settings.support==='B'?opts.slice(0,3):opts;choices.innerHTML=opts.map(o=>`<button onclick="answer(${o[2]})">${o[0]}<b>${o[1]}</b></button>`).join('');choices.classList.remove('hidden');bar.style.width='70%';speak(`${current.question} ${ins}`)}
function answer(ok){if(ok){neededHelp?supported++:independent++;const msg=`Muito bem! ${current.success}`;feedback.textContent=msg;renderScene(current,{success:true});choices.classList.add('hidden');bar.style.width='100%';speak(msg);setTimeout(finish,settings.reduced?500:1300)}else{neededHelp=true;const target=current.options.find(o=>o[2]);const msg=settings.support==='C'?'Tente novamente.':`A Estrelinha ajuda: procure ${target[1]}.`;feedback.textContent=msg;if(settings.support==='A')renderScene(current,{hint:true});speak(msg)}}
function finish(){$('independent').textContent=independent;$('supported').textContent=supported;usedSupport.textContent=`Apoio ${settings.support}`;resultText.innerHTML=`Você ajudou o Léo a praticar: <b>${current.title}</b>.`;save();show('result')}
function save(){const key='mundoSingularDemo';const data=JSON.parse(localStorage.getItem(key)||'[]');data.push({profile:settings.profile,activity:current.title,supportLevel:settings.support,independent,supported,date:new Date().toLocaleString('pt-BR')});localStorage.setItem(key,JSON.stringify(data.slice(-30)))}
function restart(){startLesson(current.id)}
function goHome(){window.speechSynthesis?.cancel();show('home')}
sensory.onclick=()=>{demoProfile.value=settings.profile;supportLevel.value=settings.support;reduced.checked=settings.reduced;quiet.checked=settings.quiet;responseTime.value=settings.response;panel.classList.remove('hidden')};
function closePanel(){settings.profile=demoProfile.value;settings.support=supportLevel.value;settings.reduced=reduced.checked;settings.quiet=quiet.checked;settings.response=responseTime.value;localStorage.setItem('mundoSingularSettings',JSON.stringify(settings));panel.classList.add('hidden');renderHome()}
renderHome();